### PR TITLE
adding ios-safari screenshots

### PR DESCRIPTION
**Pull request by nturgut**
[PR](https://github.com/flutter/engine/pull/20963) is adding capability to take ios-screenshots. These will be used as goldens.

### CODE REVIEW

**Comment by yjbanov** [comment]
I see a couple of issues:

- Every screenshot has a horizontal line at the top of the screenshot, as if the header height is not configured correctly.
- Some images do not seem to be cropped correctly. For example, https://github.com/flutter/goldens/pull/110/files#diff-38216bc9db8e3dc32cc55edc3fa069f4 is very tall, so I'd expect it to be cropped on the bottom if it doesn't fit the iPhone screen, but instead, it seems to be cropped on the right side.

**Comment by nturgut** [comment]
> I see a couple of issues:
> 
> * Every screenshot has a horizontal line at the top of the screenshot, as if the header height is not configured correctly.
> * Some images do not seem to be cropped correctly. For example, https://github.com/flutter/goldens/pull/110/files#diff-38216bc9db8e3dc32cc55edc3fa069f4 is very tall, so I'd expect it to be cropped on the bottom if it doesn't fit the iPhone screen, but instead, it seems to be cropped on the right side.

I don't see any horizontal line, can you send me a screenshot or a name or something I can use?
https://raw.githubusercontent.com/flutter/goldens/master/engine/web/backdrop_filter_clip.png
https://raw.githubusercontent.com/flutter/goldens/master/engine/web/draw_vertices_triangle_fan.png

**Comment by nturgut** [comment]
> I see a couple of issues:
> 
> * Every screenshot has a horizontal line at the top of the screenshot, as if the header height is not configured correctly.
> * Some images do not seem to be cropped correctly. For example, https://github.com/flutter/goldens/pull/110/files#diff-38216bc9db8e3dc32cc55edc3fa069f4 is very tall, so I'd expect it to be cropped on the bottom if it doesn't fit the iPhone screen, but instead, it seems to be cropped on the right side.

I adjust the scaling as we discussed offline. I also removed the header from the images that have them. PHAL

**Review by yjbanov — APPROVED** [review]
lgtm

**Review by mdebbar — APPROVED** [review]

**Comment by nturgut** [comment]
Thanks for the review!

**Pull request merged**
