### PR TITLE
[canvaskit] add text style goldens

### PR DESCRIPTION
**Pull request by yjbanov**

### CODE REVIEW

**Review by ferhatb — APPROVED** [review]
Can you please double check locale_zh, seems wrong

**Comment by yjbanov** [comment]
> Can you please double check locale_zh, seems wrong

This is expected. I'm landing a PR that fixes 2 issues, but my test is capturing as many text scenarios as possible. Some of these screenshots actually contain issues for unfixed issues. In the test I'm leaving links to the relevant issues and other PRs (https://github.com/flutter/engine/pull/23800). As we fix those issues we'll just update the goldens at the same time.

**Comment by yjbanov** [comment]
I regenerated the screenshots after merging with @hterkelsen's Noto changes. You will see that CJK goldens have improved. There's still an issue with spaces. I filed github issues for all bugs that I spotted.

PTAL

**Review by hterkelsen — APPROVED** [review]
LGTM

**Pull request merged**
