### PR TITLE
Added superellipse_shape golden image (#26295)

### PR DESCRIPTION
**Pull request by Salby**
Added golden image used for testing by superellipse_shape.

### CODE REVIEW

**Comment by dnfield** [comment]
Would it make sense to add a few with different parameters?

**Comment by Salby** [comment]
I added another test that has some uneven radii. Not sure how many we really need.

**Comment by dnfield** [comment]
Could you do one more with a larger radius?  That should be good.

**Comment by dnfield** [comment]
Great! LGTM

**Comment by dnfield** [comment]
(You'll have to update the goldens hash in your PR on flutter/flutter now to pull this in for the testing)

**Comment by Salby** [comment]
Should I delete this branch now?

**Comment by dnfield** [comment]
You can, up to you really

**Comment by Salby** [comment]
I understand :) thanks.

**Pull request merged**
